"""
Prompts for the Interaction Agent.
Generates structured interaction specs from V-spec encoding info + I-node description.
"""

BUILD_INTERACTION_SPEC_PROMPT = """You are an interaction design engineer for coordinated multi-view systems.

## Task
Given the existing structured specification for visualization views and a user's natural language description of desired interactions, translate those interactions into the structured JSON format.

## Input Data

### View Specifications
{view_specs_json}

### Interaction Requirement (from analysis plan)
{interaction_requirement}

## Target Structured Format

Output a **single JSON object** with exactly two top-level array fields:

### `source_views` (array)
Each item has:
| Field | Type | Description |
|-------|------|-------------|
| `id` | string | Source view ID (e.g., "V4") |
| `select` | string | "point", "interval", or "none" |
| `source_channels` | string[] | Encoding channels monitored (e.g., ["x"], ["x","y"]) |
| `link_field` | string | Data field used for linking (e.g., "customer_id") |
| `semantic` | string | Canonical semantic concept supplied in the view metadata (e.g., "formation") |

### `controlled_view` (array)
Each item has:
| Field | Type | Description |
|-------|------|-------------|
| `view` | string | Target view ID to control (e.g., "V1") |
| `field` | string | Data field in target view for linking (e.g., "customer_id") |
| `action` | string | "filter" or "highlight" (applies only to this target view) |
| `semantic` | string | Canonical semantic concept; must match the source semantic |

## Rules
1. `source_channels` must be encoding channel names only (e.g., ["x"]), not field names.
2. `link_field` in source and `field` in target may have different names, but their semantic metadata must describe the same canonical concept.
   Example: `argentina_formation` and `brazil_formation` can link when both have `semantic: "formation"`.
   These field values are the machine-readable contracts for the V->I and I->V edges; each must be a single field-name string, never an array or encoding channel.
3. `select` type determines interaction trigger: "point" for click/select, "interval" for brush.
4. Output only a valid JSON object with exactly two keys: "source_views" and "controlled_view".
5. Omit all explanations, comments, or non-JSON content.
6. Include one `source_views` entry for every declared V->I source and one `controlled_view` entry for every declared I->V target.
7. Choose fields from the supplied encoding fields only. Prefer semantic compatibility over identical spelling, and never invent a field or semantic label.

## Example

### Input
View Specifications: [V4: area chart, encoding x=customer_id, y=count; V1: bar chart, encoding x=customer_id, y=revenue]
Interaction Requirement: "V4 uses x-axis brush to filter V1 by customer_id"

### Output
{{"source_views": [{{"id": "V4", "select": "interval", "source_channels": ["x"], "link_field": "customer_id", "semantic": "customer_id"}}], "controlled_view": [{{"view": "V1", "field": "customer_id", "action": "filter", "semantic": "customer_id"}}]}}

Now analyze the given View Specifications and Interaction Requirement, and output the JSON. Do not include any explanation."""


VALIDATE_INTERACTION_SPEC_PROMPT = """You are a validator for interaction specifications in a coordinated multi-view visualization system.

## Input
An interaction spec generated by the system. Validate whether it is complete and correct given the available views.

### Interaction Spec
{interaction_spec_json}

### Available View Specifications
{view_specs_json}

## Validation Rules
1. Every source view `id` must exist in the available views.
2. Every controlled view `view` must exist in the available views.
3. Every source view's `link_field` must be a valid encoding field in that source view.
4. Every controlled view's `field` must be a valid encoding field in that target view.
5. `select` must be "point", "interval", or "none".
6. `action` must be "filter" or "highlight".
7. `source_channels` must contain only valid encoding channel names (x, y, color, size, etc.).
8. At least one source view must be defined.
9. At least one controlled view must be defined.

Output a JSON object with:
- "valid": boolean
- "issues": array of {{"type": string, "detail": string}} describing any problems found
- "error": string, first issue detail if invalid, empty string if valid

Do not include any explanation outside the JSON."""
